<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Toy Wonderland!</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/thankYou.css">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
<div class="thank-you-container">
    <div class="confetti-container">
        <!-- Confetti elements will be generated by JS -->
    </div>

    <div class="thank-you-card">
        <div class="toy-robot"></div>
        <div class="toy-teddy"></div>
        <div class="toy-balloon"></div>

        <div class="card-content">
            <h1 class="thank-you-title">Welcome to Toy Wonderland!</h1>
            <p class="thank-you-message">Thank you for joining our magical toy family!</p>
            <div class="thank-you-icon">🎉</div>

            <div class="progress-container">
                <div class="progress-bar">
                    <div class="progress-fill"></div>
                </div>
                <p class="progress-text">Setting up your toy adventure...</p>
            </div>

            <div class="reward-badge">
                <div class="badge-icon">🏆</div>
                <div class="badge-text">New Member Reward Unlocked!</div>
            </div>

            <a href="${pageContext.request.contextPath}/toys/home" class="explore-btn">
                Start Exploring
                <i class="fas fa-arrow-right"></i>
            </a>
        </div>
    </div>

    <div class="floating-toys">
        <div class="floating-toy car"></div>
        <div class="floating-toy blocks"></div>
        <div class="floating-toy duck"></div>
    </div>
</div>

<script src="${pageContext.request.contextPath}/js/thankYou.js"></script>
</body>
</html>