spring.application.name=ToyStore
# Server properties
server.port=8080

# Thymeleaf properties
spring.thymeleaf.cache=false

# File paths
toy.data.file=data/toys.txt

# Application properties
app.name=ToyLand
app.admin.username=admin
app.admin.password=admin123